# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testcoverage:
    if: github.event.pull_request.draft == false # Don't run if PR is draft
    name: Test and coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn global add node-gyp-cache
      - run: yarn config set node_gyp node-gyp-cache
      - run: yarn install --frozen-lockfile
      - run: yarn compile
      - run: yarn coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: 177c7477-b961-48a3-811f-49494a3d5a41
          directory: ./coverage/
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
